### PR TITLE
POT file updated

### PR DESCRIPTION
**Pull request by Hakansv**
If you merge this I'll contact Pavel for a Crowdin update.
Håkan

### CODE REVIEW

**Comment by canboat** [comment]
Thanks Håkan!

**Comment by Hakansv** [comment]
And Ive now synchronised my Github Master. The push f.   did the
trick.

Håkan

 

  _____

**Comment by nohal** [comment]
Hakan...
No need, I got the notification and have just pushed the template to Crowdin - will create a PR with the translations in a few days.

Thanks

Pavel

**Comment by Hakansv** [comment]
Ahh..Your great!

Thanks

Håkan

 

  _____

**Pull request merged**
