### PR TITLE
Hide small blobs for ARPA

### PR DESCRIPTION
**Pull request by douwefokkema**
The minimum contour length of a target can now per radar be specified in the ini file (Radar0MinContourLength). Blobs with a contour below this value will be ignored by the (M)ARPA system. This should make it possible to follow targets in a cluttered environment, as long as the targets are larger than the clutter.

### CODE REVIEW

**Comment by Hakansv** [comment]
Tested successfully by simulation as earlier. Not much clutter in the test file so no particularly test of the new feature.

**Comment by Hakansv** [comment]
Last PR shortly tested and, as desired, targets are more stable and less affected by short interruptions.
In a week or so I may have the opportunity to test the ARPA feature live.

**Comment by PacificGreen** [comment]
Working on my development environment right now but if someone has a windows installer for the plugin so that testing of Marpa/Arpa can begin I'm available.  The latest beta 2.628 does not have the Marpa functionality.  I  have Marpa working on my HDS7 so far but have to wait for boats to travel past unless I get underway.

**Comment by douwefokkema** [comment]
I have put a beta version of the setup package for BR24radar_pi with ARPA on https://www.dropbox.com/s/a6spxpctqx4divg/br24radar_pi-2.3-win32.exe?dl=0. This version is stable as far as I know. It is not released as it has not yet been tested in real life conditions at sea.
To use MARPA: click right mouse, then click "Set Arpa Target" close to or on the blob that you want to follow. A MARPA target will be created that will be handled by OCPN just like a AIS target (you can set alarm).

To use ARPA: set a guard zone and tick the ARPA button. Any blob entering the zone will become an ARPA target automatically and again be handled by OCPN.

But be aware, (M)ARPA requires a fast heading update, Preferably 10Hz  and via the radar interface. Without a good heading target tracking get unreliable.

**Comment by PacificGreen** [comment]
Thank you.  I ran into so much trouble getting wxWidgets setup on Windows 10 with the prerequisites that it was becoming annoying.  My old Visual Studio is 1200 km away for the next 10 days and that was from around 2002.

**Comment by PacificGreen** [comment]
I find that once you set the guard zone it shows the targets very precisely.  For instance I intersect the zone with the corner of a large barge on my dock and it identifies humans as arpa targets.  It also acquires them automatically.  Getting a range and a bearing from 50' is something I'm considering by changing the arc dimensions.
I notice that when I have my chartplotter on at the same time the system is very erratic.  I have the first three options checked for plugin preferences and no check boxes filled after the third.  I'm wondering what the correct setting is for target trails.  I view in overlay for the most part but can use all the screens.

**Comment by PacificGreen** [comment]
Some instability this morning but it seems to have worked out great.  Will try and get a video if we make it out again this week.


Arden

________________________________

**Comment by PacificGreen** [comment]
https://youtu.be/vbONlbmNfvk 
https://youtu.be/RJ2kcOE9DjE

I'll be spooling out the videos as time permits.  You find my channel they will all be there.

**Comment by douwefokkema** [comment]
This thread is meant to discuss the issue it relates to. As this discussion is broadening now, I suggest to continue it on the forum: http://www.cruisersforum.com/forums/showthread.php?p=2336413
As the issue addressed and merged, I will close the issue now.

**Pull request merged**
