### PR TITLE
Deleted AIS/ARPA debug info

### PR DESCRIPTION
**Pull request by Hakansv**
Debug info used for AIS detection is now needless. The function seems to work as desired.

### CODE REVIEW

**Comment by walsco** [comment]
Hi Håkan!
How far away is a beta release for Windows?
Best regards!
Walter

Den 29 juli 2017 2:51 em skrev "Håkan Svensson" <notifications@github.com>:

**Comment by Hakansv** [comment]
Walter..
We don't rely know since Kees is the master for Canboat and I think he would like to finalize ARPA also for the Radar Window(s) before release. A beta test copy including ARPA for overlay only is here:  https://www.dropbox.com/s/suzfkd01trzb9yt/br24radar_pi-2.3-win32.exe?dl=0
If you'd like to test be welcome. Bug reports are of course also appreciated. Use of ARPA description is here: http://www.cruisersforum.com/forums/f134/navico-radar-plugin-v2-0-released-170797-11.html#post2438726
Håkan

**Comment by canboat** [comment]
A short note from Jersey (still cruising) … 

Douwe and I are still finalising various issues, and the radar window ARPA functionality is not even started.

Since the previous version still works, we’re not that in a hurry to finish this in the next few weeks.

Probably by autumn.

Kees

**Comment by Hakansv** [comment]
Very good! Cruising is important! That's why we're working on features like this plugin. Please enjoy Jersey, never been there but wouldn't mind at all.
Håkan

**Comment by canboat** [comment]
Douwe is cruising somewhere in your neighborhood I believe?

**Comment by Hakansv** [comment]
Yes, we met the day before yesterday in Gothenburg. Very nice to eventually see him and his wife.

**Pull request merged**
